### ISSUE TITLE
ERROR Error Code  0 error Response Text  undefined vulsrepo report

### ISSUE THREAD

**Issue by neofallxyz** [ishiDACo/vulsrepo#168]
![Screenshot from 2020-11-17 11-16-46](https://user-images.githubusercontent.com/22272022/99346121-6e0e5200-28c6-11eb-93c5-f8210c627733.png)

Hi, when i select the result of vuls for viewing in vulsrepo, vulsrepo display like that. i am trying to copy the result/ from my vuls directory **/usr/share/vuls/result** to **/opt/vuls/result** but nothing change. what's problem here and how to fix this?
Thank you.

```
vuls dir : /usr/share/vuls/
vulsrepo : /home/ubuntu/go/src/github.com/ishiDACo/vulsrepo/
```

**Comment by ishiDACo** [comment]
Please check `vulsrepo-config.toml`.

```toml
[Server]
resultsPath  = "/opt/vuls/results"
```

If resultsPath is `/opt/vuls/results`, you need to copy `/opt/vuls/results`, not `/opt/vuls/result`.

For example,

```bash
$ pwd
/opt/vuls
$ tree .
.
└── results
    ├── 2020-11-16T07:38:02Z
    │   ├── localhost.json
    │   ├── oracle_linux7.json
    │   ├── raspberry10.json
    │   └── vuls@localhost.json
    ├── 2020-11-17T01:14:17Z
    │   └── localhost.json
    └── current -> /opt/vuls/results/2020-11-17T01:14:17Z/
```

Alternatively, rewrite `vulsrepo-config.toml` as follows, and then restart VulsRepo.

```toml
[Server]
resultsPath  = "/usr/share/vuls/result" <--- your vuls results directory
```
